name: Python CI with Artifact

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]  # Use one version for packaging

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .

    - name: Run tests with pytest
      run: |
        PYTHONPATH=. pytest

    - name: Build distribution package
      run: |
        python -m pip install build
        python -m build
      # Output goes to ./dist/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: calculator-package
        path: dist/
